# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path

# Enhanced spec file for SPP Automation Tool
block_cipher = None

# Define the main GUI entry point
gui_analysis = Analysis(
    ['spp_enhanced_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('*.sql', '.'),
        ('*.json', '.'),
    ],
    hiddenimports=[
        'spp_automation_enhanced',
        'snowflake.connector.auth',
        'snowflake.connector.auth.webbrowser',
        'snowflake.connector.network',
        'snowflake.connector.cursor',
        'snowflake.connector.connection',
        'snowflake.connector.constants',
        'snowflake.connector.errorcode',
        'snowflake.connector.errors',
        'snowflake.connector.util_text',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.offsets',
        'pandas._libs.tslibs.parsing',
        'pandas._libs.tslibs.period',
        'pandas._libs.tslibs.strptime',
        'pandas._libs.tslibs.timestamps',
        'pandas._libs.tslibs.timezones',
        'pandas._libs.tslibs.tzconversion',
        'openpyxl.cell.read_only',
        'openpyxl.chart.marker',
        'openpyxl.chart.text',
        'openpyxl.comments.comment_sheet',
        'openpyxl.compat.strings',
        'openpyxl.descriptors.serialisable',
        'openpyxl.formatting.formatting',
        'openpyxl.pivot.fields',
        'openpyxl.styles.alignment',
        'openpyxl.styles.borders',
        'openpyxl.styles.colors',
        'openpyxl.styles.differential',
        'openpyxl.styles.fills',
        'openpyxl.styles.fonts',
        'openpyxl.styles.named_styles',
        'openpyxl.styles.numbers',
        'openpyxl.styles.protection',
        'openpyxl.utils.dataframe',
        'openpyxl.workbook.defined_name',
        'openpyxl.workbook.smart_tags',
        'openpyxl.worksheet.datavalidation',
        'openpyxl.worksheet.hyperlink',
        'openpyxl.worksheet.pagebreak',
        'openpyxl.worksheet.related',
        'openpyxl.xml.constants',
        'pkg_resources.py2_warn',
        'pkg_resources.markers',
        'jwt.algorithms',
        'cryptography.hazmat.backends.openssl',
        'cryptography.hazmat.backends.openssl.rsa',
        'cryptography.hazmat.backends.openssl.dsa',
        'cryptography.hazmat.backends.openssl.ec',
        'keyring.backends',
        'defusedxml.expatreader',
        'defusedxml.expatbuilder',
        'defusedxml.sax',
        'defusedxml.minidom',
        'defusedxml.pulldom',
        'defusedxml.xmlrpc',
        'cffi.backend_ctypes',
        'idna.core',
        'idna.idnadata',
        'idna.intranges',
        'charset_normalizer.md',
        'urllib3.util.connection',
        'urllib3.util.url',
        'urllib3.util.retry',
        'urllib3.util.timeout',
        'urllib3.contrib.pyopenssl',
        'urllib3.packages.six',
        'packaging.version',
        'packaging.specifiers',
        'packaging.requirements',
        'packaging.markers',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

gui_pyz = PYZ(gui_analysis.pure, gui_analysis.zipped_data, cipher=block_cipher)

gui_exe = EXE(
    gui_pyz,
    gui_analysis.scripts,
    gui_analysis.binaries,
    gui_analysis.zipfiles,
    gui_analysis.datas,
    [],
    name='SPP_Automation_Tool_Enhanced',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Hide console window for GUI
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
    icon='hd_supply_icon.ico'
)
